openapi: 3.0.0
info:
  title: Get Task API
  version: 1.0.0
  description: Retrieve a single task by ID for the authenticated user

paths:
  /api/tasks/{id}:
    get:
      summary: Get a single task by ID
      description: |
        Returns a single task by ID if it belongs to the authenticated user.
        Returns 404 if task doesn't exist or doesn't belong to the user
        (doesn't reveal existence of other users' tasks).
      operationId: getTask
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Task UUID
          schema:
            type: string
            format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
      responses:
        '200':
          description: Task retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                title: "Buy groceries"
                description: "Milk, eggs, bread, and vegetables"
                status: "pending"
                due_date: "2026-02-15T10:00:00Z"
                created_at: "2026-02-08T12:00:00Z"
                updated_at: "2026-02-08T12:00:00Z"
        '400':
          description: Invalid task ID format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Invalid task ID format"
                code: "INVALID_ID"
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Invalid or expired token"
                code: "INVALID_TOKEN"
        '404':
          description: Task not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
                code: "TASK_NOT_FOUND"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Internal server error"
                code: "SERVER_ERROR"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 2000
          nullable: true
        status:
          type: string
          enum: [pending, completed]
        due_date:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - detail
        - code
      properties:
        detail:
          type: string
        code:
          type: string
