openapi: 3.0.0
info:
  title: Update Task API
  version: 1.0.0
  description: Update an existing task for the authenticated user

paths:
  /api/tasks/{id}:
    patch:
      summary: Update a task
      description: |
        Updates one or more fields of an existing task. Only the task owner
        can update the task. All fields are optional (partial update).
        Returns 404 if task doesn't exist or doesn't belong to the user.
      operationId: updateTask
      tags:
        - Tasks
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: Task UUID
          schema:
            type: string
            format: uuid
          example: "550e8400-e29b-41d4-a716-446655440000"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  minLength: 1
                  maxLength: 200
                  description: Updated task title
                  example: "Buy groceries and milk"
                description:
                  type: string
                  maxLength: 2000
                  nullable: true
                  description: Updated task description
                  example: "Milk, eggs, bread, vegetables, and cheese"
                status:
                  type: string
                  enum: [pending, completed]
                  description: Updated task status
                  example: "completed"
                due_date:
                  type: string
                  format: date-time
                  nullable: true
                  description: Updated due date
                  example: "2026-02-20T10:00:00Z"
            examples:
              updateTitle:
                value:
                  title: "Buy groceries and milk"
              markCompleted:
                value:
                  status: "completed"
              updateMultiple:
                value:
                  title: "Buy groceries and milk"
                  description: "Updated description"
                  status: "completed"
                  due_date: "2026-02-20T10:00:00Z"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "550e8400-e29b-41d4-a716-446655440000"
                user_id: "123e4567-e89b-12d3-a456-426614174000"
                title: "Buy groceries and milk"
                description: "Milk, eggs, bread, vegetables, and cheese"
                status: "completed"
                due_date: "2026-02-20T10:00:00Z"
                created_at: "2026-02-08T12:00:00Z"
                updated_at: "2026-02-08T14:30:00Z"
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              examples:
                emptyTitle:
                  value:
                    detail: "Title cannot be empty"
                    code: "INVALID_TITLE"
                invalidStatus:
                  value:
                    detail: "Status must be 'pending' or 'completed'"
                    code: "INVALID_STATUS"
        '401':
          description: Authentication error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Invalid or expired token"
                code: "INVALID_TOKEN"
        '404':
          description: Task not found or doesn't belong to user
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Task not found"
                code: "TASK_NOT_FOUND"
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
              example:
                detail: "Internal server error"
                code: "SERVER_ERROR"

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - status
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
        user_id:
          type: string
          format: uuid
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          maxLength: 2000
          nullable: true
        status:
          type: string
          enum: [pending, completed]
        due_date:
          type: string
          format: date-time
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    Error:
      type: object
      required:
        - detail
        - code
      properties:
        detail:
          type: string
        code:
          type: string
