openapi: 3.0.3
info:
  title: User Login API
  description: Endpoint for user authentication and JWT token issuance
  version: 1.0.0

paths:
  /api/auth/login:
    post:
      summary: Authenticate user and issue JWT token
      description: |
        Authenticates a user with email and password. Returns a JWT token valid for 15 minutes.
        User must have verified their email before login. Account lockout occurs after 5 failed attempts.
      operationId: loginUser
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  maxLength: 255
                  description: User's email address
                  example: user@example.com
                password:
                  type: string
                  minLength: 8
                  maxLength: 128
                  description: User's password
                  example: SecurePass123!
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    description: JWT access token (expires in 15 minutes)
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                  token_type:
                    type: string
                    example: bearer
                  expires_in:
                    type: integer
                    description: Token expiration time in seconds
                    example: 900
                  user:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: 550e8400-e29b-41d4-a716-446655440000
                      email:
                        type: string
                        format: email
                        example: user@example.com
        '400':
          description: Invalid request data
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
              examples:
                missingCredentials:
                  value:
                    detail: Email and password are required
                invalidEmail:
                  value:
                    detail: Invalid email format
        '401':
          description: Authentication failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
              examples:
                invalidCredentials:
                  value:
                    detail: Invalid credentials
                unverifiedEmail:
                  value:
                    detail: Email not verified. Please check your email for verification link.
        '403':
          description: Account locked
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                  locked_until:
                    type: string
                    format: date-time
              example:
                detail: Account locked due to too many failed login attempts. Try again in 15 minutes.
                locked_until: "2026-02-08T12:30:00Z"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: Authentication service unavailable

components:
  schemas:
    LoginRequest:
      type: object
      required:
        - email
        - password
      properties:
        email:
          type: string
          format: email
          maxLength: 255
        password:
          type: string
          minLength: 8
          maxLength: 128

    LoginResponse:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: integer
        user:
          type: object
          properties:
            id:
              type: string
              format: uuid
            email:
              type: string
              format: email

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string

    AccountLockedResponse:
      type: object
      properties:
        detail:
          type: string
        locked_until:
          type: string
          format: date-time
